language: objective-c

before_script:
    - brew update
    - brew uninstall xctool && brew install xctool

script:
    # xcodebuild -project TestApp.xcodeproj -scheme TestApp -sdk iphonesimulator -configuration Release test
    - xctool -project TestApp.xcodeproj -scheme TestApp -sdk iphonesimulator -configuration Release test -test-sdk iphonesimulator
